# path to a directory with all packages
storage: ../tmp/local-registry/storage

listen: localhost:4872

auth:
  auth-memory:
    users:
      verdacciouser:
        name: verdacciouser
        password: passw0rd

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    maxage: 30m
    fail_timeout: 10m
    timeout: 600s
    cache: false
  yarn:
    url: https://registry.yarnpkg.com
    max_fails: 100
    maxage: 30m
    fail_timeout: 10m
    timeout: 600s
    cache: false

packages:
  '@*/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: warn }
