# path to a directory with all packages
storage: ../../../tmp/local-registry/storage

listen: localhost:4872

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    maxage: 30m
    fail_timeout: 10m
    timeout: 600s
    cache: false

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    access: $all

    # allow all users (including non-authenticated users) to publish/publish packages
    publish: $all
    unpublish: $all

    # if package is not available locally, proxy requests to 'yarn' registry
    proxy: npmjs

# log settings
logs:
  type: stdout
  format: pretty
  level: warn
